package com.example.amitapp;

public class Main {

    public static void main(String[] args) {
        int[] nums = new int[10]; // Initialize an array with a length of 10

        nums[3] = 10; // Assign the value 10 to the element at index 3

        // Print the entire nums array
        for (int i = 0; i < nums.length; i++) {
            System.out.print(nums[i] + " ");
        }
    }
}


-- -- OUTPUT 
-- -- 0 0 0 10 0 0 0 0 0 0
-- THE ARAY WITH OUT INSERT WILL BE 0
